services:
  planner-front:
    image: 'ghcr.io/tori-tih/planner-front:master'
    ports:
      - '80:80'
      - '443:443'
  discovery:
    image: 'ghcr.io/geiier/e-journal-discovery:master'
    ports:
      - '8761:8761'
  nodejs:
    image: 'ghcr.io/tori-tih/planner-nodejs:master'
    ports:
      - '3001:3001'
    environment:
      - 'EUREKA_HOST=discovery'
      - 'EUREKA_PORT=8761'
      - 'HOST_NAME=nodejs'
  auth:
    container_name: 'auth'
    image: 'ghcr.io/geiier/e-journal-auth:master'
    ports:
      - '8081:8081'
    environment:
      - 'APP_NAME=planner-auth'
      - 'POSTGRES_URL=jdbc:postgresql://postgres:5432/calendar'
      - 'POSTGRES_PASSWORD=1111'
      - 'POSTGRES_USER=tori'
      - 'EUREKA_URI=http://discovery:8761/eureka'
  planner:
    container_name: 'planner'
    image: 'ghcr.io/tori-tih/planner-back:master'
    ports:
      - '8046:8046'
    environment:
      - 'POSTGRES_URL=jdbc:postgresql://postgres:5432/calendar'
      - 'POSTGRES_PASSWORD=1111'
      - 'POSTGRES_USER=tori'
      - 'EUREKA_URI=http://discovery:8761/eureka'
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=calendar'
      - 'POSTGRES_PASSWORD=1111'
      - 'POSTGRES_USER=tori'
    ports:
      - '5454:5432'