server:
  port: 8046
spring:
  datasource:
    url: '${POSTGRES_URL}'
    password: '${POSTGRES_PASSWORD}'
    username: '${POSTGRES_USER}'
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        use_sql_comments: true
        format_sql: true
        jdbc:
          time_zone: Europe/Samara
    hibernate:
      ddl-auto: update
    generate-ddl: true
  application:
    name: planner-back

auth:
  baseUrl: ${AUTH_URI:http://planner-auth}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}:${server.port}
  instance:
    preferIpAddress: true